### ISSUE TITLE
Question: Why was String-db used to generate the interaction network instead of utilizing previous AB relationships in fava?

### ISSUE THREAD

**Issue by Starlitnightly** [mikelkou/fava#3]
Hi there,

I just wanted to say that I think you've done a fantastic job with the tutorial. The work you've presented has great potential for mining protein interaction networks in single-cell data.

However, I have a question regarding the use of the String-db database in the last step of the tutorial. Why did you choose to use String-db to generate the interaction network instead of utilizing the previous AB relationships to build the protein network directly?

I'm curious about the rationale behind this decision and whether there are specific advantages to using String-db in this context. Could you please provide some insights on this?

Thank you!

Zehua

**Comment by mikelkou** [comment]
Hi,

Thank you so much for appreciating our work. To begin with, your point is valid and probably I should revise the tutorials to make it clearer. The main focus of FAVA is to create the network, so you don't really need to use any additional information on top of that. I added String-db mainly because it has some really nice visualizations.

However, using String-db, which includes information from various source, like the whole literature and in the latest version also from single cell data, could be useful as a reference for your study. You can compare the networks generated by FAVA with your dataset and the ones from String-db. It'll give you a chance to see any differences based on existing literature or based on a coexpression network from a healthy single cell atlas.

However, as mentioned above, it is indeed possible to directly use the AB interactions produced by FAVA, and not follow up with STRING networks. 

Thanks for your comment!

**Comment by Starlitnightly** [comment]
> Hi,
> 
> Thank you so much for appreciating our work. To begin with, your point is valid and probably I should revise the tutorials to make it clearer. The main focus of FAVA is to create the network, so you don't really need to use any additional information on top of that. I added String-db mainly because it has some really nice visualizations.
> 
> However, using String-db, which includes information from various source, like the whole literature and in the latest version also from single cell data, could be useful as a reference for your study. You can compare the networks generated by FAVA with your dataset and the ones from String-db. It'll give you a chance to see any differences based on existing literature or based on a coexpression network from a healthy single cell atlas.
> 
> However, as mentioned above, it is indeed possible to directly use the AB interactions produced by FAVA, and not follow up with STRING networks.
> 
> Thanks for your comment!

Hi,

I previously wrote a function to visualise interactions, based on `networkx` and `matplotlib`, and the relevant code is available at https://github.com/Starlitnightly/omicverse/blob/master/omicverse/utils/_plot.py. You can use my code for network visualisation. 

I have provided two different examples showing [directed](https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_cellphonedb/#network-of-celltype-analysis) and [undirected](https://omicverse.readthedocs.io/en/latest/Tutorials-bulk/t_network/#string-ppi-network) graphs respectively, which may be of some help in visualising fava.

I also plan to integrate fava into `omicverse`. fava is really a very nice insight into protein network analysis of single cells. Once again, my compliments on your work

Zehua

**Comment by mikelkou** [comment]
This is really cool. Thank you.
