### ISSUE TITLE
Prevent log2 transformation in already log2-transformed data

### ISSUE THREAD

**Issue by bazoogis** [mikelkou/fava#8]
Dear @mikelkou, 

We are really grateful for all your work on FAVA.

Reading your updated fava.py code, we believe that the code does not efficiently check whether input data are already log2-transformed or not.

We propose that you change line 116 in fava.py from:

    if np.all(expr >= 0):

to:

    if np.all(expr >= 0) and np.max(expr)-np.min(expr) >= 40:

as the condition of checking for negative values is not enough. The value of 40 is arbitrary and you are free to change it.

40 corresponds to the log2 transformation of an unrealistic amount of 1 trillion reads while it is small for a gene count difference between the largest and the smallest number.

Best Regards,
Dr. Ioannis Michalopoulos and Vasileios Zogopoulos

**Comment by mikelkou** [comment]
Hello @bazoogis,

Thank you for the suggestion. I was mainly trying to prevent negative values but I can understand that it might not be optimal for catching the log transformation. I will have it done soon and let you know.

Best,
Mikaela

**Comment by mikelkou** [comment]
Hello,

I am closing this issue now. I checked again and I agree with you but in case that your data are log normalized you can always use the `log2_normalization=False`, so there no problems. It seems fairly arbitrary for now to set some value. The problem was when you have negative values which is what I am trying to capture.

Best,
Mikaela

**Comment by mikelkou** [comment]
Hello,

I am closing this issue now. I checked again and I agree with you but in case that your data are log normalized you can always use the `log2_normalization=False`, so there no problems. It seems fairly arbitrary for now to set some value. The problem was when you have negative values which is what I am trying to capture.

Best,
Mikaela
